site_name: Moqups User Documentation

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.integrate
    

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - General Operations: general-operations.md