site_name: Moqups User Documentation

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.integrate
    

  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Creat an Account: create-an-account.md
  - General Operations: general-operations.md
  - Work with UML Class Shapes: work-with-UML-class-shapes.md
  - Connect Classes Using Lines: connect-classes-using-lines.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md