site_name: My Docs

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
